# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-08-04 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.IntegerField()),
                ('ename', models.CharField(max_length=30)),
                ('ejob', models.CharField(blank=True, max_length=30, null=True)),
                ('esal', models.FloatField()),
                ('deptno', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='phno',
            field=models.IntegerField(default=0),
        ),
    ]
