# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-08-08 12:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210808_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postlu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2021, 8, 8, 12, 31, 34, 988446, tzinfo=utc))),
                ('published_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 8, 12, 31, 34, 988446, tzinfo=utc)),
        ),
    ]
